### PR TITLE
fix: fix compilation error message

### LINKED ISSUE #64: no codeframe in cypress dev mode
it seems e.originalStack is no longer being serialized or something when cypress is in dev mode, so no code-frame is shown in run mode or open mode

Cypress `4.0.0`

### PR DESCRIPTION
**Pull request by Bkucera**
append error to error.message instead of error.stack
- this fixes strange issue where the stack will not contain the code-frame and only keep the stacktrace
- also fixes issue with `Error: Webpack Compilation Error` not showing up in the error
- makes hack around `e.originalStack` unnecessary 

fix #64

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -125,7 +123,11 @@ const preprocessor = (options = {}) => {
 
       if (stats.hasErrors()) {
         err = new Error('Webpack Compilation Error')
-        err.stack = jsonStats.errors.join('\n\n')
+        err.message += `\n${jsonStats.errors
+        // remove stack trace lines since they're useless for debugging
+        .map((err) => err.replace(/\n\s*at.*/g, '').replace(/From previous event:\n?/g, ''))
```
Comment (Bkucera) [inline index.js]: this same logic is used in test runner to strip stack trace lines, so we're just moving this logic up
https://github.com/cypress-io/cypress/blob/master/packages/server/lib/plugins/preprocessor.coffee#L16

Comment (bahmutov) [reply index.js]: ughh, this is so so weird - why have 3 lines of code inside a string template?

Comment (Bkucera) [reply index.js]: eslint auto-fixed to that when i tried to add `'\n'`

**Comment by bahmutov** [comment]
I have noticed this says "fix:" but does not reference an issue and does not have a test

File: index.js (hunk 1 above)
Comment (Bkucera) [reply index.js]: fixed

**Comment by Bkucera** [comment]
snapshot is updated, but I'll add an assertion
