### PR TITLE
fix: fix file watching on compilation error

### LINKED ISSUE #65: compilation errors do not cause browser to refesh spec
### Is this a Feature or Bug?
bug

### Current behavior:
upon compilation error, the browser does not reload automatically, and requires a manual refresh to see it 

### Desired behavior:
compilation errors should be displayed in the browser runner without having to manually reload the page

### How to reproduce:
in this repo:
```sh
npx cypress open
[select compile-error.js]
[make a change + save compile-error.js]
[notice new syntax error is not reflected in browser gui until manual refresh]
```

### PR DESCRIPTION
**Pull request by Bkucera**
fix issue where compilation error does not cause cypress to refetch the spec and display the error without a manual page reload.

fix #65 
- use `finally()` instead of `tap()` so `file.emit('rerun')` will be called for both the failing/success code paths

#### also
- use async fs methods in e2e spec
- upgrade sinon, mocha
- add testing against `webpack@latest` to potentially catch new issues (maybe this should be a separate automation, and we should test fixed previous versions for compatability)

#### how to reproduce error (before this change):
in this repo:
```sh
npx cypress open
[select compile-error.js]
[make a change + save compile-error.js]
[notice new syntax error is not reflected in browser gui until manual refresh]
```

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -157,7 +162,7 @@ const preprocessor = (options = {}) => {
       latestBundle = createDeferred()
       bundles[filePath] = latestBundle.promise
 
-      bundles[filePath].tap(() => {
+      bundles[filePath].finally(() => {
```
Comment (Bkucera) [inline index.js]: this should be the only functional change
